# JetPack 5.0.2 / CUDA 11.2
FROM nvcr.io/nvidia/l4t-base:35.1.0

ENV TZ=Etc/UTC
ENV DEBIAN_FRONTEND=noninteractive
#ENV LD_LIBRARY_PATH=/usr/local/cuda-12.2/targets/aarch64-linux/lib:${LD_LIBRARY_PATH}

# Install system packages
RUN apt update && apt install -y \
    python3-pip python3-opencv libgl1 wget vim \
    cuda-cudart-11-4 libcublas-11-4 libcufft-11-4 libcurand-11-4 libcusolver-11-4 libcusparse-11-4 \
    libcudnn8 



# Copy wheel and app files into image
COPY local_installs/* /tmp/
WORKDIR /app

# Install Python dependencies
RUN pip3 install --no-cache-dir /tmp/onnxruntime_gpu-1.15.1-cp38-cp38-linux_aarch64.whl
RUN pip3 install --no-cache-dir numpy==1.24.4 opencv-python
