## ??? MASIVE SPACE ??? 

FROM nvcr.io/nvidia/l4t-ml:r36.2.0-py3

ENV TZ=Etc/UTC
ENV DEBIAN_FRONTEND=noninteractive

# Install system packages
RUN apt update && apt install -y \
    python3-pip wget vim

# Copy wheel and app files into image
COPY local_installs/* /tmp/
WORKDIR /app

# Install Python dependencies
RUN pip3 install --no-cache-dir /tmp/onnxruntime_gpu-1.18.0-cp310-cp310-linux_aarch64.whl \
 && pip3 install --no-cache-dir numpy==1.24.4 opencv-python