 # JetPack 4.4 GA, CUDA 10.2
FROM nvcr.io/nvidia/l4t-base:r32.4.3         

ENV TZ=Etc/UTC
ENV DEBIAN_FRONTEND=noninteractive
#ENV LD_LIBRARY_PATH=/usr/local/cuda-12.2/targets/aarch64-linux/lib:${LD_LIBRARY_PATH}

RUN apt-get update && apt-get install -y --no-install-recommends \
    gnupg curl ca-certificates \
    python3.8 python3.8-distutils python3-pip python3-opencv \
    libgl1 wget vim apt-utils


# Make python3 → python3.8 and upgrade pip
RUN update-alternatives --install /usr/bin/python3 python3 /usr/bin/python3.8 10 && \
    python3 -m pip install --upgrade pip setuptools wheel 

# Add NVIDIA L4T APT repo for JetPack 4.4 (L4T r32.4.3)
RUN echo "deb https://repo.download.nvidia.com/jetson/common r32.4 main" > /etc/apt/sources.list.d/nvidia-l4t.list && \
    echo "deb https://repo.download.nvidia.com/jetson/t210 r32.4 main" >> /etc/apt/sources.list.d/nvidia-l4t.list && \
    apt-key adv --fetch-keys https://repo.download.nvidia.com/jetson/jetson-ota-public.asc && \
    apt-get update


# Install cuda packages
RUN apt update &&  apt-get install -y --no-install-recommends \
    cuda-cudart-10-2 libcublas10 libcudnn8 cuda-toolkit-10-2 

# Copy wheel and app files into image
COPY local_installs/* /tmp/
WORKDIR /app

# Install Python dependencies
RUN pip3 install --no-cache-dir /tmp/onnxruntime_gpu-1.11.0-cp38-cp38-linux_aarch64.whl
RUN pip3 install --no-cache-dir numpy==1.24.4 opencv-python
